<a href="https://colab.research.google.com/github/1911521010UlfatmiHanifa/Kelompok7-APM/blob/main/GaussianNaiveBayess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("drive/MyDrive/APM/Prostate_Cancer.csv")

In [ ]:
dataset.head()

id  diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                 0      23       12        151   954       0.143   
1   2                 1       9       13        133  1326       0.143   
2   3                 0      21       27        130  1203       0.125   
3   4                 0      14       16         78   386       0.070   
4   5                 0       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 100 non-null    int64  
 1   diagnosis_result   100 non-null    int64  
 2   radius             100 non-null    int64  
 3   texture            100 non-null    int64  
 4   perimeter          100 non-null    int64  
 5   area               100 non-null    int64  
 6   smoothness         100 non-null    float64
 7   compactness        100 non-null    float64
 8   symmetry           100 non-null    float64
 9   fractal_dimension  100 non-null    float64
dtypes: float64(4), int64(6)
memory usage: 7.9 KB


In [ ]:
dataset.empty

False

In [ ]:
x = dataset.drop(["diagnosis_result"], axis = 1)
x.head()

id  radius  texture  perimeter  area  smoothness  compactness  symmetry  \
0   1      23       12        151   954       0.143        0.278     0.242   
1   2       9       13        133  1326       0.143        0.079     0.181   
2   3      21       27        130  1203       0.125        0.160     0.207   
3   4      14       16         78   386       0.070        0.284     0.260   
4   5       9       19        135  1297       0.141        0.133     0.181   

   fractal_dimension  
0              0.079  
1              0.057  
2              0.060  
3              0.097  
4              0.059

In [ ]:
y = dataset["diagnosis_result"]
y.head()

0    0
1    1
2    0
3    0
4    0
Name: diagnosis_result, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [ ]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)

In [ ]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[9.33569626e-01, 6.64303738e-02],
       [2.08098549e-01, 7.91901451e-01],
       [6.21120637e-01, 3.78879363e-01],
       [9.99389300e-01, 6.10699588e-04],
       [9.98528759e-01, 1.47124088e-03],
       [9.99998535e-01, 1.46490044e-06],
       [1.88662769e-02, 9.81133723e-01],
       [9.99572513e-01, 4.27487228e-04],
       [1.49700312e-01, 8.50299688e-01],
       [8.01799249e-03, 9.91982008e-01],
       [3.35002504e-02, 9.66499750e-01],
       [1.44618694e-02, 9.85538131e-01],
       [9.99422933e-01, 5.77067301e-04],
       [9.99999999e-01, 5.64439703e-10],
       [9.99999075e-01, 9.24513469e-07],
       [6.26464176e-01, 3.73535824e-01],
       [9.99338349e-01, 6.61650887e-04],
       [1.39079942e-01, 8.60920058e-01],
       [2.61341823e-03, 9.97386582e-01],
       [8.80842264e-01, 1.19157736e-01]])

In [ ]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[10,  2],
       [ 2,  6]])

In [ ]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        12
           1       0.75      0.75      0.75         8

    accuracy                           0.80        20
   macro avg       0.79      0.79      0.79        20
weighted avg       0.80      0.80      0.80        20

